[[constraint]]
  name = "github.com/openfaas/faas"
  version = "0.10.1"

[[constraint]]
  name = "github.com/openfaas/faas-provider"
  version = "0.8.1"

[[constraint]]
  name = "github.com/hashicorp/nomad"
  version = "0.7.0"

[[constraint]]
  name = "github.com/hashicorp/vault"
  version = "v0.9.6"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "github.com/mitchellh/mapstructure"
  version = "v1.1.2"

[prune]
  go-tests = true
  unused-packages = true
